---
config:
- management_ip_address: 204.1.2.5
  site_name_hierarchy: Global/USA/SAN JOSE/SJ_BLD23
  provisioning: true
  force_provisioning: false
- management_ip_address: 204.1.2.69
  site_name_hierarchy: Global/USA/SAN JOSE/SJ_BLD23
  provisioning: true
  force_provisioning: false
- management_ip_address: 204.1.2.3
  site_name_hierarchy: Global/USA/SAN JOSE/SJ_BLD23
  provisioning: true
  force_provisioning: false
- management_ip_address: 204.1.216.27
  site_name_hierarchy: Global/USA/SAN JOSE/SJ_BLD23/FLOOR4
  provisioning: false
  force_provisioning: false
- management_ip_address: 204.1.216.26
  site_name_hierarchy: Global/USA/SAN JOSE/SJ_BLD23/FLOOR4
  provisioning: false
  force_provisioning: false
- management_ip_address: 204.1.216.6
  site_name_hierarchy: Global/USA/New York/NY_BLD1/FLOOR1
  provisioning: false
  force_provisioning: false
- management_ip_address: 204.192.106.4
  site_name_hierarchy: Global/USA/SAN JOSE/SJ_BLD23/FLOOR4
  provisioning: false
  force_provisioning: false
- management_ip_address: 204.192.106.3
  site_name_hierarchy: Global/USA/SAN JOSE/SJ_BLD23/FLOOR4
  provisioning: false
  force_provisioning: false
- management_ip_address: 204.192.106.2
  site_name_hierarchy: Global/USA/SAN JOSE/SJ_BLD23/FLOOR4
  provisioning: false
  force_provisioning: false
- management_ip_address: 204.192.3.40
  site_name_hierarchy: Global/USA/New York/NY_BLD1
  provisioning: false
  force_provisioning: false
- management_ip_address: 204.1.2.4
  site_name_hierarchy: Global/a_swim/swim_test1
  provisioning: false
  force_provisioning: false
- management_ip_address: 204.192.6.200
  site_name_hierarchy: Global/USA/New York/NY_BLD1
  provisioning: false
  force_provisioning: false
  managed_ap_locations: []
- management_ip_address: 204.192.6.202
  site_name_hierarchy: Global/USA/New York/NY_BLD2
  provisioning: false
  force_provisioning: false
  managed_ap_locations: []
- management_ip_address: 204.192.4.200
  site_name_hierarchy: Global/USA/SAN JOSE/SJ_BLD23
  provisioning: false
  force_provisioning: false
  managed_ap_locations: []
