---
# Playbook Configure to generate Network Switch Profiles on Cisco Catalyst Center
- name: Generate the playbook for the Network Switch Profiles from Cisco Catalyst Center
  hosts: localhost
  connection: local
  gather_facts: false  # This space must be "no". It was set to false due to formatting errors.but the correct value is "no".
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Generate Network Switch Profiles workflow playbook
      cisco.dnac.brownfield_network_profile_switching_playbook_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: gathered
        config:
          # ========================================================================================
          # Scenario 1: Generate all all switch profile configurations
          # ========================================================================================
          - file_path: "tmp/brownfield_network_profile_switching_workflow_playbook.yml"
            generate_all_configurations: true

          # ========================================================================================
          # Scenario 2: Generate switch profile configurations based on profile name global filters
          # ========================================================================================
          - file_path: "tmp/brownfield_network_profile_switching_workflow_playbook_profilebase.yml"
            global_filters:
              profile_name_list:
                - Enterprise_Switching_Profile
                - Campus_Core_Switching

          # ========================================================================================
          # Scenario 3: Generate switch profile configurations based on template name global filters
          # ========================================================================================
          - file_path: "tmp/brownfield_network_profile_switching_workflow_playbook_templatebase.yml"
            global_filters:
              day_n_template_list:
                - evpn_l2vn_anycast_template

          # ========================================================================================
          # Scenario 4: Generate switch profile configurations based on site name global filters
          # ========================================================================================
          - file_path: "tmp/brownfield_network_profile_switching_workflow_playbook_sitebase.yml"
            global_filters:
              site_list:
                - Global/USA/SAN JOSE/SJ_BLD21/FLOOR1
                - Global/USA/SAN JOSE/SJ_BLD21/FLOOR2
      register: result_custom_path
      tags: [generate_all, custom_path]
