---
# Generate playbook configuration for accesspoint location workflow on Cisco Catalyst Center
- name: Generate the playbook for the Access Point Location workflow manger
  hosts: localhost
  connection: local
  gather_facts: false  # This space must be "no". It was set to false due to formatting errors.but the correct value is "no".
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Generate Access Point Location workflow playbook
      cisco.dnac.brownfield_accesspoint_location_playbook_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: gathered
        config:
          # ========================================================================================
          # Scenario 1: Generate all all Access Point Location position configurations
          # ========================================================================================
          - file_path: "tmp/brownfield_accesspoint_location_workflow_playbook.yml"
            generate_all_configurations: true

          # ========================================================================================
          # Scenario 2: Generate Access Point Location configurations based on Site list filters
          # ========================================================================================
          - file_path: "tmp/brownfield_accesspoint_location_workflow_playbook_site_base.yml"
            global_filters:
              site_list:
                - Global/USA/SAN JOSE/SJ_BLD23/FLOOR1
                - Global/USA/SAN JOSE/SJ_BLD23/FLOOR2
                - Global/USA/SAN JOSE/SJ_BLD23/FLOOR4

          # ========================================================================================
          # Scenario 3: Generate Access Point Location configurations based on Planned AP list filters
          # ========================================================================================
          - file_path: "tmp/brownfield_accesspoint_location_workflow_playbook_PAP_base.yml"
            global_filters:
              planned_accesspoint_list:
                - ap_test_auto-1
                - ap_test_auto-3

          # ========================================================================================
          # Scenario 4: Generate Access Point Location configurations based on Real ap list filters
          # ========================================================================================
          - file_path: "tmp/brownfield_accesspoint_location_workflow_playbook_real_ap_base.yml"
            global_filters:
              real_accesspoint_list:
                - AP687D.B402.1614-AP-Test6
                - Cisco_9120AXE_IP4-01-Test2

          # ========================================================================================
          # Scenario 5: Generate Access Point Location configurations based on accesspoint model filters
          # ========================================================================================
          - file_path: "tmp/brownfield_accesspoint_location_workflow_playbook_accesspoint_model_base.yml"
            global_filters:
              accesspoint_model_list:
                - AP9120E
                - CW9172I

          # ========================================================================================
          # Scenario 6: Generate accesspoint location configurations based on mac address list filters
          # ========================================================================================
          - file_path: "tmp/brownfield_accesspoint_location_workflow_playbook_mac_address_base.yml"
            global_filters:
              mac_address_list:
                - cc:6e:2a:e1:02:40

      register: result_custom_path
      tags: [generate_all, custom_path]
