---
# Generate playbook configuration for network wireless profiles workflow on Cisco Catalyst Center
- name: Generate the playbook for the Network Wireless Profile workflow manager
  hosts: localhost
  connection: local
  gather_facts: false  # This space must be "no". It was set to false due to formatting errors.but the correct value is "no".
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Generate Network Wireless Profiles workflow playbook
      cisco.dnac.network_profile_wireless_playbook_config_generator:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: gathered
        config:
          # ========================================================================================
          # Scenario 1: Generate all all wireless profile configurations
          # ========================================================================================
          - file_path: "tmp/network_profile_wireless_workflow_playbook.yml"
            generate_all_configurations: true

          # ========================================================================================
          # Scenario 2: Generate wireless profile configurations based on profile name list filter
          # ========================================================================================
          - file_path: "tmp/network_profile_wireless_workflow_playbook_profilebase.yml"
            global_filters:
              profile_name_list:
                - Enterprise_Wireless_Profile
                - Campus_Wireless_Profile

          # ========================================================================================
          # Scenario 3: Generate wireless profile configurations based on ssid list filters
          # ========================================================================================
          - file_path: "tmp/network_profile_wireless_workflow_playbook_ssidbase.yml"
            global_filters:
              ssid_list:
                - GUEST
                - Corporate_WiFi

          # ========================================================================================
          # Scenario 4: Generate wireless profile configurations based on ap zone list filters
          # ========================================================================================
          - file_path: "tmp/network_profile_wireless_workflow_playbook_apzonebase.yml"
            global_filters:
              ap_zone_list:
                - AP_Zone_North
                - HQ_AP_Zone

          # ========================================================================================
          # Scenario 5: Generate wireless profile configurations based on feature template list filters
          # ========================================================================================
          - file_path: "tmp/network_profile_wireless_workflow_playbook_feature_template_base.yml"
            global_filters:
              feature_template_list:
                - Default AAA_Radius_Attributes_Configuration
                - Default CleanAir 6GHz Design

          # ========================================================================================
          # Scenario 6: Generate wireless profile configurations based on day n template list filters
          # ========================================================================================
          - file_path: "tmp/network_profile_wireless_workflow_playbook_templatebase.yml"
            global_filters:
              day_n_template_list:
                - Ans Wireless DayN 1

          # ========================================================================================
          # Scenario 7: Generate wireless profile configurations based on interface list filters
          # ========================================================================================
          - file_path: "tmp/network_profile_wireless_workflow_playbook_interfacebase.yml"
            global_filters:
              additional_interface_list:
                - VLAN_22

          # ========================================================================================
          # Scenario 8: Generate wireless profile configurations based on site list filters
          # ========================================================================================
          - file_path: "tmp/network_profile_wireless_workflow_playbook_sitebase.yml"
            global_filters:
              site_list:
                - Global/USA/SAN JOSE/SJ_BLD20/FLOOR1
                - Global/USA/SAN JOSE/SJ_BLD20/FLOOR2

      register: result_custom_path
      tags: [generate_all, custom_path]
